run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: "NO"
        subdir: 4omini/Baseline
    log:
        debug_en: False
gpt: 
    model: gpt-4o-mini-2024-07-18
autoline: 
    probset: 
        path: data/HDLBits/HDLBits_data.jsonl
        mutant_path: data/HDLBits/HDLBits_data_mutants.jsonl
    onlyrun: TBgensimeval
    promptscript: directgen
    timeout: 40
    save_compile: False
    debug:
        max: 0