run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: "NO"
        subdir: Claude_Sonnet35/AutoBench
    log:
        debug_en: False
gpt: 
    model: claude-3-5-sonnet-20240620
autoline: 
    probset: 
        path: data/HDLBits/HDLBits_data.jsonl
        mutant_path: data/HDLBits/HDLBits_data_mutants.jsonl
    onlyrun: TBgensimeval
    promptscript: pychecker
    timeout: 40
    save_compile: False
    debug:
        max: 3