# time: 2024/02/22 14:27:00 v2.1pre
run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: new_autoline_test_rule110
        subdir: test
gpt: 
    model: 4
autoline: 
    probnum: single
    probset: data/HDLBits/HDLBits_data_miniset.jsonl
    mutantset: data/HDLBits/HDLBits_data_miniset_mutants.jsonl
    single: 
        taskid: rule110